<a href="https://colab.research.google.com/github/SiyumiJayawardhane/Iris_Flower_Classification_ML_Project/blob/Model_training/IFC_Model_Training.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
#Mount drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
# Load Cleaned Dataset
data_path = "/content/drive/MyDrive/Projects/IFC/cleaned_iris.csv"
data = pd.read_csv(data_path)

In [4]:
# Splitting Features and Target
X = data.drop(columns=['Species'])
y = data['Species']

In [5]:
# Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [6]:
# Standardization
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Logistic Regression

In [7]:
# Logistic Regression Model
log_reg = LogisticRegression()
log_reg.fit(X_train, y_train)
y_train_pred_log_reg = log_reg.predict(X_train)
y_test_pred_log_reg = log_reg.predict(X_test)

In [8]:
# Evaluate Logistic Regression
print("Logistic Regression Accuracy (Train):", accuracy_score(y_train, y_train_pred_log_reg))
print("Classification Report (Train):\n", classification_report(y_train, y_train_pred_log_reg))
print("Logistic Regression Accuracy (Test):", accuracy_score(y_test, y_test_pred_log_reg))
print("Classification Report (Test):\n", classification_report(y_test, y_test_pred_log_reg))
print("Confusion Matrix (Test):\n", confusion_matrix(y_test, y_test_pred_log_reg))

Logistic Regression Accuracy (Train): 0.9736842105263158
Classification Report (Train):
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        37
           1       0.95      0.97      0.96        38
           2       0.97      0.95      0.96        39

    accuracy                           0.97       114
   macro avg       0.97      0.97      0.97       114
weighted avg       0.97      0.97      0.97       114

Logistic Regression Accuracy (Test): 0.896551724137931
Classification Report (Test):
               precision    recall  f1-score   support

           0       1.00      1.00      1.00         8
           1       0.83      0.91      0.87        11
           2       0.89      0.80      0.84        10

    accuracy                           0.90        29
   macro avg       0.91      0.90      0.90        29
weighted avg       0.90      0.90      0.90        29

Confusion Matrix (Test):
 [[ 8  0  0]
 [ 0 10  1]
 [ 0  2  8]]


In [10]:
# Save Logistic Regression Model
import joblib
joblib.dump(log_reg, "/content/drive/MyDrive/Projects/IFC/logistic_regression_model.pkl")

['/content/drive/MyDrive/Projects/IFC/logistic_regression_model.pkl']

# K-Nearest Neighbors

In [11]:
# K-Nearest Neighbors Model
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
y_train_pred_knn = knn.predict(X_train)
y_test_pred_knn = knn.predict(X_test)

In [12]:
# Evaluate KNN
print("KNN Accuracy (Train):", accuracy_score(y_train, y_train_pred_knn))
print("Classification Report (Train):\n", classification_report(y_train, y_train_pred_knn))
print("KNN Accuracy (Test):", accuracy_score(y_test, y_test_pred_knn))
print("Classification Report (Test):\n", classification_report(y_test, y_test_pred_knn))
print("Confusion Matrix (Test):\n", confusion_matrix(y_test, y_test_pred_knn))

KNN Accuracy (Train): 0.9649122807017544
Classification Report (Train):
               precision    recall  f1-score   support

           0       1.00      0.97      0.99        37
           1       0.93      0.97      0.95        38
           2       0.97      0.95      0.96        39

    accuracy                           0.96       114
   macro avg       0.97      0.97      0.97       114
weighted avg       0.97      0.96      0.97       114

KNN Accuracy (Test): 0.896551724137931
Classification Report (Test):
               precision    recall  f1-score   support

           0       1.00      1.00      1.00         8
           1       0.83      0.91      0.87        11
           2       0.89      0.80      0.84        10

    accuracy                           0.90        29
   macro avg       0.91      0.90      0.90        29
weighted avg       0.90      0.90      0.90        29

Confusion Matrix (Test):
 [[ 8  0  0]
 [ 0 10  1]
 [ 0  2  8]]


In [13]:
# Save KNN Model
joblib.dump(knn, "/content/drive/MyDrive/Projects/IFC/knn_model.pkl")

['/content/drive/MyDrive/Projects/IFC/knn_model.pkl']